### ISSUE TITLE
🔒 Небезопасное копирование в буфер обмена

### ISSUE THREAD

**Issue by alplottw** [shumilovsergey/tg-pass-vault#3]
## Проблема
Текущая реализация копирования паролей в буфер обмена небезопасна:
```javascript
navigator.clipboard.writeText(password);
alert('Password copied!');
```

## Риски
1. Пароль остаётся в буфере обмена неограниченное время
2. Любое приложение может получить доступ к скопированному паролю
3. Отсутствует очистка буфера обмена
4. Использование `alert()` блокирует UI и выглядит непрофессионально

## Предлагаемое решение
1. Добавить автоматическую очистку буфера обмена через таймер
2. Использовать современные уведомления вместо alert
3. Добавить визуальную индикацию процесса копирования

Пример реализации:
```javascript
async function secureClipboardCopy(text, timeout = 30000) {
  try {
    await navigator.clipboard.writeText(text);
    
    // Показываем красивое уведомление
    showNotification('Скопировано в буфер обмена', 'success');
    
    // Очищаем буфер через 30 секунд
    setTimeout(async () => {
      await navigator.clipboard.writeText('');
      showNotification('Буфер обмена очищен', 'info');
    }, timeout);
    
  } catch (err) {
    showNotification('Ошибка при копировании', 'error');
    console.error('Clipboard error:', err);
  }
}

function showNotification(message, type) {
  const notification = document.createElement('div');
  notification.className = `notification ${type}`;
  notification.textContent = message;
  
  document.body.appendChild(notification);
  
  // Удаляем уведомление через 3 секунды
  setTimeout(() => {
    notification.remove();
  }, 3000);
}
```

Также нужно добавить CSS для уведомлений:
```css
.notification {
  position: fixed;
  bottom: 20px;
  right: 20px;
  padding: 10px 20px;
  border-radius: 4px;
  color: white;
  animation: slideIn 0.3s ease;
}

.notification.success {
  background: #4caf50;
}

.notification.error {
  background: #f44336;
}

.notification.info {
  background: #2196f3;
}

@keyframes slideIn {
  from {
    transform: translateX(100%);
    opacity: 0;
  }
  to {
    transform: translateX(0);
    opacity: 1;
  }
}
```

## Приоритет
Средний (безопасность/UX)
