### ISSUE TITLE
🚀 Оптимизация производительности и обработка ошибок

### ISSUE THREAD

**Issue by alplottw** [shumilovsergey/tg-pass-vault#4]
## Проблема
В текущей реализации есть несколько проблем с производительностью и обработкой ошибок:

1. Отсутствует обработка ошибок при загрузке данных:
```javascript
async function loadPasswords() {
  const res = await fetch('data.json');
  const passwords = await res.json();
  // Нет обработки ошибок
}
```

2. Отсутствует кэширование данных
3. Нет индикации загрузки
4. Нет обработки офлайн-режима

### 1. Добавить обработку ошибок и индикацию загрузки
```javascript
async function loadPasswords() {
  const loader = document.querySelector('.loader');
  const errorContainer = document.querySelector('.error-container');
  
  try {
    loader.style.display = 'block';
    errorContainer.style.display = 'none';
    
    const res = await fetch('data.json');
    if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
    
    const passwords = await res.json();
    return passwords;
    
  } catch (err) {
    console.error('Failed to load passwords:', err);
    errorContainer.textContent = 'Не удалось загрузить пароли. Проверьте подключение.';
    errorContainer.style.display = 'block';
    return [];
    
  } finally {
    loader.style.display = 'none';
  }
}
```

### 2. Добавить кэширование данных
```javascript
const CACHE_KEY = 'password_vault_data';
const CACHE_DURATION = 1000 * 60 * 5; // 5 минут

async function getPasswords() {
  // Проверяем кэш
  const cached = localStorage.getItem(CACHE_KEY);
  if (cached) {
    const { data, timestamp } = JSON.parse(cached);
    if (Date.now() - timestamp < CACHE_DURATION) {
      return data;
    }
  }
  
  // Если кэша нет или он устарел, загружаем новые данные
  const passwords = await loadPasswords();
  
  // Кэшируем результат
  localStorage.setItem(CACHE_KEY, JSON.stringify({
    data: passwords,
    timestamp: Date.now()
  }));
  
  return passwords;
}
```

### 3. Добавить поддержку офлайн-режима
```javascript
// Регистрируем Service Worker
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js')
      .then(registration => console.log('ServiceWorker registered'))
      .catch(err => console.error('ServiceWorker registration failed:', err));
  });
}

// sw.js
const CACHE_NAME = 'password-vault-v1';
const ASSETS = [
  '/',
  '/index.html',
  '/style.css',
  '/script.js',
  '/data.json'
];

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache => cache.addAll(ASSETS))
  );
});

self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request)
      .then(response => response || fetch(event.request))
  );
});
```

### 4. Добавить индикатор состояния подключения
```javascript
function updateOnlineStatus() {
  const status = document.querySelector('.connection-status');
  if (navigator.onLine) {
    status.textContent = '🟢 Онлайн';
    status.classList.remove('offline');
    status.classList.add('online');
  } else {
    status.textContent = '🔴 Офлайн';
    status.classList.remove('online');
    status.classList.add('offline');
  }
}

window.addEventListener('online', updateOnlineStatus);
window.addEventListener('offline', updateOnlineStatus);
updateOnlineStatus(); // Initial check
```

## CSS для новых элементов
```css
.loader {
  display: none;
  /* Стили для спиннера */
}

.error-container {
  display: none;
  color: #f44336;
  padding: 10px;
  margin: 10px 0;
  border: 1px solid #f44336;
  border-radius: 4px;
}

.connection-status {
  position: fixed;
  top: 10px;
  right: 10px;
  padding: 5px 10px;
  border-radius: 4px;
  font-size: 12px;
}

.connection-status.online {
  background: #4caf50;
  color: white;
}

.connection-status.offline {
  background: #f44336;
  color: white;
}
```

## Приоритет
Средний (производительность/UX)
